model:
  pretrained_path: "path/to/pretrained/model"
  model_type: "transformer"  # or other model types
  device: "cuda"  # or "cpu"

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.0001
  optimizer: "adam"
  weight_decay: 0.01
  gradient_clip_val: 1.0

fine_tuning:
  layers_to_freeze: []  # empty list means fine-tune all layers
  dropout_rate: 0.1
  warmup_steps: 100

data:
  train_path: "path/to/train/data"
  val_path: "path/to/val/data"
  test_path: "path/to/test/data"
  num_workers: 4

logging:
  log_dir: "logs"
  save_dir: "checkpoints"
  log_every_n_steps: 100
  tensorboard: true 